# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - '**/*.yaml'
      - '**/*.md'

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - '**/*.yaml'
      - '**/*.md'

pool:
  vmImage: 'ubuntu-latest'


steps:
  - task: Checkout@1
    displayName: 'Checkout code'

  - task: UseNode@1
    inputs:
      version: '22.x'
    displayName: 'Set up Node.js'

  - script: npm install -g yarn
    displayName: 'Install Yarn'

  - script: yarn install
    displayName: 'Install dependencies'

  - script: yarn run test
    displayName: 'Run tests'
