trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - '**/*.yaml'
      - '**/*.md'

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - '**/*.yaml'
      - '**/*.md'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    displayName: 'Checkout code'

  - task: UseNode@1
    inputs:
      version: '22.x'
    displayName: 'Set up Node.js'

  - script: npm install -g yarn
    displayName: 'Install Yarn'

  - script: yarn install
    displayName: 'Install dependencies'

  - script: yarn run test
    displayName: 'Run tests'

- template: send-discord-notification.yaml
  parameters:
    status: $(Build.Status)
    definitionName: $(Build.DefinitionName)
    branch: $(Build.SourceBranchName)
    buildId: $(Build.BuildId)
    projectUri: $(System.TeamFoundationCollectionUri)$(System.TeamProject)/
