# CI - Nível 1: Disparo manual a partir de 1 clique

name: 'Execução Manual'

# regras de disparos
on:
  workflow_dispacth: 

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:

    # maquina que o job vai rodar. https://github.com/actions/runner-images
    runs-on: ubuntu-latest

    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalação das dependências
      - name: Insatalando dependências
        run: yarn

      # instalação do Playwright
      - name: Instalando Playwright
        run: yarn playwright install
      
      # executar os testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e