# CI de Nível 01 - Disparo manual a partir de 1 clique
# nome do nosso 'pipeline'
name: 'E2E - trigger'
# regras de disparo (gatilhos/triggers)
# gatilho de exec manual = workflow_dispatch
on:
  workflow_dispatch:
# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-trigger:
    runs-on: ubuntu-latest
    steps: 
      # clone do projeto
      - uses: actions/checkout@v4
      # Node install
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Yarn install
        run: npm install -g yarn
      
      - name: Dependencies install
        run: yarn
      
      - name: Playwright install
        run: yarn playwright install

      - name: Running E2E tests
        run: yarn run e2e